services:
  dauth-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: https://api.dauth.debuggerstechnologies.com
        VITE_FRONTEND_URL: https://dauth.debuggerstechnologies.com
    image: sivarajan001/debuggerstech-dauth-site:latest
    container_name: dauth-frontend
    restart: unless-stopped

    environment:
      - VITE_BACKEND_URL=https://api.dauth.debuggerstechnologies.com
      - VITE_FRONTEND_URL=https://dauth.debuggerstechnologies.com
      - BACKEND_URL=https://api.dauth.debuggerstechnologies.com
      - FRONTEND_URL=https://dauth.debuggerstechnologies.com

    ports:
      - "94:80"
